// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseProto.proto

package protobuf.proto;

public final class BaseProto {
    private BaseProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite)registry);
    }

    public interface BaseRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BaseRequest)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The uri.
         */
        java.lang.String getUri();

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The bytes for uri.
         */
        com.google.protobuf.ByteString getUriBytes();

        /**
         * <pre>
         * body
         * </pre>
         *
         * <code>bytes body = 2;</code>
         *
         * @return The body.
         */
        com.google.protobuf.ByteString getBody();
    }

    /**
     * Protobuf type {@code BaseRequest}
     */
    public static final class BaseRequest extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:BaseRequest)
        BaseRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use BaseRequest.newBuilder() to construct.
        private BaseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BaseRequest() {
            uri_ = "";
            body_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new BaseRequest();
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return protobuf.proto.BaseProto.internal_static_BaseRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return protobuf.proto.BaseProto.internal_static_BaseRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(protobuf.proto.BaseProto.BaseRequest.class,
                    protobuf.proto.BaseProto.BaseRequest.Builder.class);
        }

        public static final int URI_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object uri_ = "";

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The uri.
         */
        @java.lang.Override
        public java.lang.String getUri() {
            java.lang.Object ref = uri_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                java.lang.String s = bs.toStringUtf8();
                uri_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The bytes for uri.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getUriBytes() {
            java.lang.Object ref = uri_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                uri_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        public static final int BODY_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * body
         * </pre>
         *
         * <code>bytes body = 2;</code>
         *
         * @return The body.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
            }
            if (!body_.isEmpty()) {
                output.writeBytes(2, body_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
            }
            if (!body_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, body_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof protobuf.proto.BaseProto.BaseRequest)) {
                return super.equals(obj);
            }
            protobuf.proto.BaseProto.BaseRequest other = (protobuf.proto.BaseProto.BaseRequest)obj;

            if (!getUri().equals(other.getUri())) {
                return false;
            }
            if (!getBody().equals(other.getBody())) {
                return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + URI_FIELD_NUMBER;
            hash = (53 * hash) + getUri().hashCode();
            hash = (37 * hash) + BODY_FIELD_NUMBER;
            hash = (53 * hash) + getBody().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static protobuf.proto.BaseProto.BaseRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(protobuf.proto.BaseProto.BaseRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code BaseRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:BaseRequest)
            protobuf.proto.BaseProto.BaseRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return protobuf.proto.BaseProto.internal_static_BaseRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return protobuf.proto.BaseProto.internal_static_BaseRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(protobuf.proto.BaseProto.BaseRequest.class,
                        protobuf.proto.BaseProto.BaseRequest.Builder.class);
            }

            // Construct using protobuf.proto.BaseProto.BaseRequest.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                uri_ = "";
                body_ = com.google.protobuf.ByteString.EMPTY;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return protobuf.proto.BaseProto.internal_static_BaseRequest_descriptor;
            }

            @java.lang.Override
            public protobuf.proto.BaseProto.BaseRequest getDefaultInstanceForType() {
                return protobuf.proto.BaseProto.BaseRequest.getDefaultInstance();
            }

            @java.lang.Override
            public protobuf.proto.BaseProto.BaseRequest build() {
                protobuf.proto.BaseProto.BaseRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public protobuf.proto.BaseProto.BaseRequest buildPartial() {
                protobuf.proto.BaseProto.BaseRequest result = new protobuf.proto.BaseProto.BaseRequest(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(protobuf.proto.BaseProto.BaseRequest result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.uri_ = uri_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.body_ = body_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof protobuf.proto.BaseProto.BaseRequest) {
                    return mergeFrom((protobuf.proto.BaseProto.BaseRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(protobuf.proto.BaseProto.BaseRequest other) {
                if (other == protobuf.proto.BaseProto.BaseRequest.getDefaultInstance()) {
                    return this;
                }
                if (!other.getUri().isEmpty()) {
                    uri_ = other.uri_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
                    setBody(other.getBody());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                uri_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                body_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object uri_ = "";

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @return The uri.
             */
            @Override
            public java.lang.String getUri() {
                java.lang.Object ref = uri_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    java.lang.String s = bs.toStringUtf8();
                    uri_ = s;
                    return s;
                } else {
                    return (java.lang.String)ref;
                }
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @return The bytes for uri.
             */
            @Override
            public com.google.protobuf.ByteString getUriBytes() {
                java.lang.Object ref = uri_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                    uri_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @param value The uri to set.
             * @return This builder for chaining.
             */
            public Builder setUri(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                uri_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUri() {
                uri_ = getDefaultInstance().getUri();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @param value The bytes for uri to set.
             * @return This builder for chaining.
             */
            public Builder setUriBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                uri_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * body
             * </pre>
             *
             * <code>bytes body = 2;</code>
             *
             * @return The body.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <pre>
             * body
             * </pre>
             *
             * <code>bytes body = 2;</code>
             *
             * @param value The body to set.
             * @return This builder for chaining.
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                body_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * body
             * </pre>
             *
             * <code>bytes body = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBody() {
                bitField0_ = (bitField0_ & ~0x00000002);
                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:BaseRequest)
        }

        // @@protoc_insertion_point(class_scope:BaseRequest)
        private static final protobuf.proto.BaseProto.BaseRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new protobuf.proto.BaseProto.BaseRequest();
        }

        public static protobuf.proto.BaseProto.BaseRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BaseRequest> PARSER =
            new com.google.protobuf.AbstractParser<BaseRequest>() {
                @java.lang.Override
                public BaseRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

        public static com.google.protobuf.Parser<BaseRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<BaseRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public protobuf.proto.BaseProto.BaseRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface BaseResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BaseResponse)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The uri.
         */
        java.lang.String getUri();

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The bytes for uri.
         */
        com.google.protobuf.ByteString getUriBytes();

        /**
         * <pre>
         * 数据
         * </pre>
         *
         * <code>bytes data = 2;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();

        /**
         * <pre>
         * 响应代码，成功返回：200
         * </pre>
         *
         * <code>int32 code = 3;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <pre>
         * 响应描述
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The msg.
         */
        java.lang.String getMsg();

        /**
         * <pre>
         * 响应描述
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString getMsgBytes();
    }

    /**
     * Protobuf type {@code BaseResponse}
     */
    public static final class BaseResponse extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:BaseResponse)
        BaseResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use BaseResponse.newBuilder() to construct.
        private BaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BaseResponse() {
            uri_ = "";
            data_ = com.google.protobuf.ByteString.EMPTY;
            msg_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new BaseResponse();
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return protobuf.proto.BaseProto.internal_static_BaseResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return protobuf.proto.BaseProto.internal_static_BaseResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(protobuf.proto.BaseProto.BaseResponse.class,
                    protobuf.proto.BaseProto.BaseResponse.Builder.class);
        }

        public static final int URI_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object uri_ = "";

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The uri.
         */
        @java.lang.Override
        public java.lang.String getUri() {
            java.lang.Object ref = uri_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                java.lang.String s = bs.toStringUtf8();
                uri_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 路径
         * </pre>
         *
         * <code>string uri = 1;</code>
         *
         * @return The bytes for uri.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getUriBytes() {
            java.lang.Object ref = uri_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                uri_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        public static final int DATA_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * 数据
         * </pre>
         *
         * <code>bytes data = 2;</code>
         *
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static final int CODE_FIELD_NUMBER = 3;
        private int code_ = 0;

        /**
         * <pre>
         * 响应代码，成功返回：200
         * </pre>
         *
         * <code>int32 code = 3;</code>
         *
         * @return The code.
         */
        @java.lang.Override
        public int getCode() {
            return code_;
        }

        public static final int MSG_FIELD_NUMBER = 4;
        @SuppressWarnings("serial")
        private volatile java.lang.Object msg_ = "";

        /**
         * <pre>
         * 响应描述
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The msg.
         */
        @java.lang.Override
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 响应描述
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The bytes for msg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uri_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(2, data_);
            }
            if (code_ != 0) {
                output.writeInt32(3, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uri_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uri_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, data_);
            }
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, code_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof protobuf.proto.BaseProto.BaseResponse)) {
                return super.equals(obj);
            }
            protobuf.proto.BaseProto.BaseResponse other = (protobuf.proto.BaseProto.BaseResponse)obj;

            if (!getUri().equals(other.getUri())) {
                return false;
            }
            if (!getData().equals(other.getData())) {
                return false;
            }
            if (getCode() != other.getCode()) {
                return false;
            }
            if (!getMsg().equals(other.getMsg())) {
                return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + URI_FIELD_NUMBER;
            hash = (53 * hash) + getUri().hashCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static protobuf.proto.BaseProto.BaseResponse parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(protobuf.proto.BaseProto.BaseResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code BaseResponse}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:BaseResponse)
            protobuf.proto.BaseProto.BaseResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return protobuf.proto.BaseProto.internal_static_BaseResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return protobuf.proto.BaseProto.internal_static_BaseResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(protobuf.proto.BaseProto.BaseResponse.class,
                        protobuf.proto.BaseProto.BaseResponse.Builder.class);
            }

            // Construct using protobuf.proto.BaseProto.BaseResponse.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                uri_ = "";
                data_ = com.google.protobuf.ByteString.EMPTY;
                code_ = 0;
                msg_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return protobuf.proto.BaseProto.internal_static_BaseResponse_descriptor;
            }

            @java.lang.Override
            public protobuf.proto.BaseProto.BaseResponse getDefaultInstanceForType() {
                return protobuf.proto.BaseProto.BaseResponse.getDefaultInstance();
            }

            @java.lang.Override
            public protobuf.proto.BaseProto.BaseResponse build() {
                protobuf.proto.BaseProto.BaseResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public protobuf.proto.BaseProto.BaseResponse buildPartial() {
                protobuf.proto.BaseProto.BaseResponse result = new protobuf.proto.BaseProto.BaseResponse(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(protobuf.proto.BaseProto.BaseResponse result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.uri_ = uri_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.data_ = data_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.code_ = code_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.msg_ = msg_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof protobuf.proto.BaseProto.BaseResponse) {
                    return mergeFrom((protobuf.proto.BaseProto.BaseResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(protobuf.proto.BaseProto.BaseResponse other) {
                if (other == protobuf.proto.BaseProto.BaseResponse.getDefaultInstance()) {
                    return this;
                }
                if (!other.getUri().isEmpty()) {
                    uri_ = other.uri_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                uri_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                data_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 24: {
                                code_ = input.readInt32();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 34: {
                                msg_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object uri_ = "";

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @return The uri.
             */
            @Override
            public java.lang.String getUri() {
                java.lang.Object ref = uri_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    java.lang.String s = bs.toStringUtf8();
                    uri_ = s;
                    return s;
                } else {
                    return (java.lang.String)ref;
                }
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @return The bytes for uri.
             */
            @Override
            public com.google.protobuf.ByteString getUriBytes() {
                java.lang.Object ref = uri_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                    uri_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @param value The uri to set.
             * @return This builder for chaining.
             */
            public Builder setUri(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                uri_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUri() {
                uri_ = getDefaultInstance().getUri();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 路径
             * </pre>
             *
             * <code>string uri = 1;</code>
             *
             * @param value The bytes for uri to set.
             * @return This builder for chaining.
             */
            public Builder setUriBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                uri_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
             *
             * @return The data.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <pre>
             * 数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                data_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 数据
             * </pre>
             *
             * <code>bytes data = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000002);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private int code_;

            /**
             * <pre>
             * 响应代码，成功返回：200
             * </pre>
             *
             * <code>int32 code = 3;</code>
             *
             * @return The code.
             */
            @java.lang.Override
            public int getCode() {
                return code_;
            }

            /**
             * <pre>
             * 响应代码，成功返回：200
             * </pre>
             *
             * <code>int32 code = 3;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {

                code_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 响应代码，成功返回：200
             * </pre>
             *
             * <code>int32 code = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000004);
                code_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object msg_ = "";

            /**
             * <pre>
             * 响应描述
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @return The msg.
             */
            @Override
            public java.lang.String getMsg() {
                java.lang.Object ref = msg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    java.lang.String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (java.lang.String)ref;
                }
            }

            /**
             * <pre>
             * 响应描述
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @return The bytes for msg.
             */
            @Override
            public com.google.protobuf.ByteString getMsgBytes() {
                java.lang.Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <pre>
             * 响应描述
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                msg_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 响应描述
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsg() {
                msg_ = getDefaultInstance().getMsg();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 响应描述
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                msg_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:BaseResponse)
        }

        // @@protoc_insertion_point(class_scope:BaseResponse)
        private static final protobuf.proto.BaseProto.BaseResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new protobuf.proto.BaseProto.BaseResponse();
        }

        public static protobuf.proto.BaseProto.BaseResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BaseResponse> PARSER =
            new com.google.protobuf.AbstractParser<BaseResponse>() {
                @java.lang.Override
                public BaseResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

        public static com.google.protobuf.Parser<BaseResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<BaseResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public protobuf.proto.BaseProto.BaseResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_BaseRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_BaseRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_BaseResponse_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_BaseResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {"\n\017BaseProto.proto\"(\n\013BaseRequest\022\013\n\003uri\030"
            + "\001 \001(\t\022\014\n\004body\030\002 \001(\014\"D\n\014BaseResponse\022\013\n\003u"
            + "ri\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\022\014\n\004code\030\003 \001(\005\022\013\n\003"
            + "msg\030\004 \001(\tB\020\n\016protobuf.protob\006proto3"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_BaseRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_BaseRequest_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BaseRequest_descriptor,
                new java.lang.String[] {"Uri", "Body",});
        internal_static_BaseResponse_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_BaseResponse_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_BaseResponse_descriptor,
                new java.lang.String[] {"Uri", "Data", "Code", "Msg",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
