// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ConnectProto.proto

// Protobuf Java Version: 3.25.1
package protobuf.proto;

public final class ConnectProto {

    private ConnectProto() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite)registry);
    }

    public interface SecurityRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SecurityRequest)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 用于校验：是否是合法的连接
         * </pre>
         *
         * <code>string code = 1;</code>
         *
         * @return The code.
         */
        java.lang.String getCode();

        /**
         * <pre>
         * 用于校验：是否是合法的连接
         * </pre>
         *
         * <code>string code = 1;</code>
         *
         * @return The bytes for code.
         */
        com.google.protobuf.ByteString getCodeBytes();
    }

    /**
     * Protobuf type {@code SecurityRequest}
     */
    public static final class SecurityRequest extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:SecurityRequest)
        SecurityRequestOrBuilder {

        private static final long serialVersionUID = 0L;

        // Use SecurityRequest.newBuilder() to construct.
        private SecurityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SecurityRequest() {
            code_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new SecurityRequest();
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return protobuf.proto.ConnectProto.internal_static_SecurityRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return protobuf.proto.ConnectProto.internal_static_SecurityRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(protobuf.proto.ConnectProto.SecurityRequest.class,
                    protobuf.proto.ConnectProto.SecurityRequest.Builder.class);
        }

        public static final int CODE_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object code_ = "";

        /**
         * <pre>
         * 用于校验：是否是合法的连接
         * </pre>
         *
         * <code>string code = 1;</code>
         *
         * @return The code.
         */
        @java.lang.Override
        public java.lang.String getCode() {
            java.lang.Object ref = code_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                java.lang.String s = bs.toStringUtf8();
                code_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 用于校验：是否是合法的连接
         * </pre>
         *
         * <code>string code = 1;</code>
         *
         * @return The bytes for code.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getCodeBytes() {
            java.lang.Object ref = code_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                code_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof protobuf.proto.ConnectProto.SecurityRequest)) {
                return super.equals(obj);
            }
            protobuf.proto.ConnectProto.SecurityRequest other = (protobuf.proto.ConnectProto.SecurityRequest)obj;

            if (!getCode().equals(other.getCode())) {
                return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static protobuf.proto.ConnectProto.SecurityRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(protobuf.proto.ConnectProto.SecurityRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code SecurityRequest}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:SecurityRequest)
            protobuf.proto.ConnectProto.SecurityRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return protobuf.proto.ConnectProto.internal_static_SecurityRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return protobuf.proto.ConnectProto.internal_static_SecurityRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(protobuf.proto.ConnectProto.SecurityRequest.class,
                        protobuf.proto.ConnectProto.SecurityRequest.Builder.class);
            }

            // Construct using protobuf.proto.ConnectProto.SecurityRequest.newBuilder()
            private Builder() {

            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return protobuf.proto.ConnectProto.internal_static_SecurityRequest_descriptor;
            }

            @java.lang.Override
            public protobuf.proto.ConnectProto.SecurityRequest getDefaultInstanceForType() {
                return protobuf.proto.ConnectProto.SecurityRequest.getDefaultInstance();
            }

            @java.lang.Override
            public protobuf.proto.ConnectProto.SecurityRequest build() {
                protobuf.proto.ConnectProto.SecurityRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public protobuf.proto.ConnectProto.SecurityRequest buildPartial() {
                protobuf.proto.ConnectProto.SecurityRequest result =
                    new protobuf.proto.ConnectProto.SecurityRequest(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(protobuf.proto.ConnectProto.SecurityRequest result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof protobuf.proto.ConnectProto.SecurityRequest) {
                    return mergeFrom((protobuf.proto.ConnectProto.SecurityRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(protobuf.proto.ConnectProto.SecurityRequest other) {
                if (other == protobuf.proto.ConnectProto.SecurityRequest.getDefaultInstance()) {
                    return this;
                }
                if (!other.getCode().isEmpty()) {
                    code_ = other.code_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                code_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object code_ = "";

            /**
             * <pre>
             * 用于校验：是否是合法的连接
             * </pre>
             *
             * <code>string code = 1;</code>
             *
             * @return The code.
             */
            public java.lang.String getCode() {
                java.lang.Object ref = code_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    java.lang.String s = bs.toStringUtf8();
                    code_ = s;
                    return s;
                } else {
                    return (java.lang.String)ref;
                }
            }

            /**
             * <pre>
             * 用于校验：是否是合法的连接
             * </pre>
             *
             * <code>string code = 1;</code>
             *
             * @return The bytes for code.
             */
            public com.google.protobuf.ByteString getCodeBytes() {
                java.lang.Object ref = code_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((java.lang.String)ref);
                    code_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <pre>
             * 用于校验：是否是合法的连接
             * </pre>
             *
             * <code>string code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 用于校验：是否是合法的连接
             * </pre>
             *
             * <code>string code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                code_ = getDefaultInstance().getCode();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 用于校验：是否是合法的连接
             * </pre>
             *
             * <code>string code = 1;</code>
             *
             * @param value The bytes for code to set.
             * @return This builder for chaining.
             */
            public Builder setCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:SecurityRequest)
        }

        // @@protoc_insertion_point(class_scope:SecurityRequest)
        private static final protobuf.proto.ConnectProto.SecurityRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new protobuf.proto.ConnectProto.SecurityRequest();
        }

        public static protobuf.proto.ConnectProto.SecurityRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SecurityRequest> PARSER =
            new com.google.protobuf.AbstractParser<SecurityRequest>() {
                @java.lang.Override
                public SecurityRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

        public static com.google.protobuf.Parser<SecurityRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SecurityRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public protobuf.proto.ConnectProto.SecurityRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_SecurityRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_SecurityRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {"\n\022ConnectProto.proto\"\037\n\017SecurityRequest\022"
            + "\014\n\004code\030\001 \001(\tB\020\n\016protobuf.protob\006proto3"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_SecurityRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_SecurityRequest_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_SecurityRequest_descriptor,
                new java.lang.String[] {"Code",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
